### ISSUE TITLE
Sparse Grid Feedback

### ISSUE THREAD

**Issue by Mylancook** [Foundations-of-Applied-Mathematics/Lab-Development#1035]
I have put up the basic lab.  I'm still working on the last part (I can get the grid points and values, but am working on getting the correct coefficients.  Any feedback will be appreciated.

**Comment by tkchris93** [comment]
* The doc string for the function in Problem 1 needs to match the Lab Standards
* On page 3, it would probably be good to specify that f(x) is approximately equal, not equal.
* The lab name in the header of each page needs to be adjusted
* Here's the biggie: this is the solution (I believe) to your coefficient issue. I was able to get everything working perfectly for problems 1 and 2.
CHANGE: 

currently says:
    c_nm = f(p) - sum sum phi_st(p)
It should be:
    c_nm = t(p) - sum sum c_st*phi_st(p)  <---- just include the c_st. All bounds are the same.

This has worked for everything I have tried so far.

* Lastly, I'm having a hard time making the transition to multiple dimensions. It kinda felt like the pysg.py file was a magic black box. I am not exactly sure what it's doing. I hope the algorithm fix will help you to get that working. As of now I'm not exactly sure how to do Problem 3.

Let me know if you need more info on any of this.

**Comment by shanemcq18** [comment]
We need to decide if we're keeping this lab or not.

**Comment by shanemcq18** [comment]
There is a missing file, `gridpoints.pdf` that should be in the repo for a figure. Do @jmorrise or @Mylancook know where that is? Also, is this lab being orphaned or not?

See #1095

**Comment by Mylancook** [comment]
I can get that file, and yes, it is being orphaned, so far as I know.

**Comment by shanemcq18** [comment]
@Mylancook did this file ever get merged in? (Just in case...)
