### ISSUE TITLE
1-D Optimization Methods

### ISSUE THREAD

**Issue by davidreber** [Foundations-of-Applied-Mathematics/Lab-Development#1202]
Vision: To help students be comfortable with all the techniques of 1-d optimization. This will prepare them for later line-search methods in higher-dimensional optimization.

- Methods to use:
    - Newton's
        - [ ] just review
    - Secant
        - [ ] just review
    - Golden Ratio
        - [ ] code up
    - Wolfe conditions/Armelio condition
        - [ ] code up
            - Guess, backtrack, use stopping criteria.
- [ ] Compare the Newton and Secant methods
    - [ ] Which situations are best for using each?
    - [ ] Explore the tradeoff between the rate of convergence and cost per iterations.
        - "A quick answer can be better than a perfect answer."

**Comment by shanemcq18** [comment]
Closing in favor of #1306.
