### ISSUE TITLE
Hosting Data Sets

### ISSUE THREAD

**Issue by tkchris93** [Foundations-of-Applied-Mathematics/Lab-Development#1214]
@shanemcq18 How are we handling large datasets? The dataset for the Bokeh lab is a 38M zip file. Are we waiting on something with the new website? Are we still using www.acme.byu/data?

**Comment by shanemcq18** [comment]
I need to have another discussion with @jhumpherys about this when he's back in town, but I think hosting them on the web is the best idea. Git really isn't built for large data storage.

We should definitely create a master list of all data files and the labs that they correspond to though.

**Comment by shanemcq18** [comment]
See [this page of the Wiki](https://github.com/Foundations-of-Applied-Mathematics/Labs/wiki/File-Dependencies-Index) for a list of the labs, the names of their specifications files, and their data/auxiliary files. Let's update this page as we go (I believe anyone can edit it) so we at least know the names of the data files that belong to each lab, especially since many of those files aren't stored in this repository.

**Comment by shanemcq18** [comment]
[Git LFS](https://git-lfs.github.com/) might be the solution we're looking for. Basically you install this extra git tool, then you tag certain files or types of files for large file storage, and they are stored on a separate server elsewhere. A pointer to the file remains in the original repository.

To get enough space for this I think we would have to slightly upgrade our [git LFS Billing plan](https://help.github.com/articles/billing-plans-for-git-large-file-storage/), but it's pretty cheap.

As a short term solution, I am compiling and updating all data sets on my desktop. I'll hand off the updated folder to @jhumpherys and he'll update [acme.byu.edu/data](acme.byu.edu/data). I'm going to try to organize the data by Volume, if possible.

**Comment by jhumpherys** [comment]
Let's see if there's an educational discount of free.

**Comment by shanemcq18** [comment]
Gave @jhumpherys an updated version of the folder containing all data for all ACME labs, sorted by volume. I'm hanging on to the old folder, just in case, but once Jeff updates [acme.byu.edu/data](acme.byu.edu/data) we're in good shape for this semester.

**Comment by shanemcq18** [comment]
[acme.byu.edu/data](acme.byu.edu/data) is now up to date.
Also, we now have free access to Git LFS, which means we can get that `Data` repository up and running.

**Comment by shanemcq18** [comment]
See the first iteration of a Data repository [here](https://github.com/Foundations-of-Applied-Mathematics/Data) (the repo is private for now). I find myself thinking that it would make more sense to put the data with the individual labs in their folders with specifications. We're going to need a large bibliography for the data (original source, if/how modified, etc.) eventually.
