### ISSUE TITLE
Facial Recognition [Summer 2016]

### ISSUE THREAD

**Issue by jmorrise** [Foundations-of-Applied-Mathematics/Lab-Development#1235]
This lab has already been looked at and thought about by lots of smart people. I don't want to make any drastic changes, but there a few edits I think it needs.

I'd like to redo the beginning of this lab, and here's why. The "eigenfaces" problem falls under the umbrella of Principal Component Analysis. PCA is important in data science and modeling. It's basically projecting your data into a lower-dimensional subspace to analyze it, and one big way to do it is with the SVD like in this lab. PCA can be applied to other image classification problems (like the digit recognition problem which the students have already seen) as well as non-image problems. The lab introduction, however, calls the algorithm to be presented _eigenfaces_ and gives the impression that it only applies to facial recognition. It would be nice if the students could realize that they were trying out one application of a much larger topic area. 

Besides that, the math needs to be gone over carefully to make sure it is both accurate and straightforward to follow. I think the "Project to a Subspace" section in particular could use editing.

Content changes:
- Edit objective
- [x] Rework the introduction to introduce PCA
- [x] Edit explanation of why and how we project to a subspace
- [x] Clarify math explanations throughout the lab 
- [x] Wording changes and grammar

Structure/ordering changes:
- [x] Refine the purpose of Problem 1 (purpose: to make sure the student can load and show the faces without errors). Take everything else out of the problem.
- [x] Have the students write an image showing function, instead of providing the function.
- [x] Introduce the object-oriented structure in Problem 2.
- [x] Place all helper code (getFaces and the class outline) either in the spec file or in the appendix.
- [x] Remove old code from repository
- [x] Create an example iPython notebook version

**Comment by shanemcq18** [comment]
I am 100% a fan of briefly introducing PCA. In fact there are a few references to PCA in the orphaned [Image Recognition](https://github.com/Foundations-of-Applied-Mathematics/Labs/tree/8f730fcdb94aebafb4a7b3908c6fd82c1087df5e/Labs/Orphans/ImageRecognition) lab and in the Volume 3 [PCA-LSI](https://github.com/Foundations-of-Applied-Mathematics/Labs/tree/5249de08f49210c6074408d938d0cd439f603285/Labs/MachineLearning/PCA-LSI) assignment (that we never did), if that helps.

**Comment by jmorrise** [comment]
Awesome, thanks.

I worked on this for a while today, wrote about principal component analysis, edited the problems, and then got to the math later on. I realized that the math explained in this lab is all about how the SVD solves the least squares problem. 
When I was researching, the justification for using the SVD in this algorithm didn't have to do with minimizing least squares. The least squares approach seems barely related to what I was thinking of with PCA. It doesn't really explain the significance of the eigenfaces themselves - that the first eigenface represents the most variance across the set of faces, the second eigenface represents the second most variance, and so on. 
So the math included here seems odd to me. With the math as is, introducing PCA doesn't make much sense. But all this was written by someone smarter and wiser than me, and I hesitate to go throwing in new theorems. 
Should I ask a professor about it? Or just leave it? Does it even matter if the "right" mathematical explanation is in the lab, as long as the problems make sense and the code runs?

**Comment by shanemcq18** [comment]
The Jarvis says that it's not really a problem, and that PCA actually basically _is_ just using the SVD. We should definitely at least mention that what we do in the lab is sometimes called PCA, but there's probably no need for an overhaul.
Anything to add, @tylerjarvis?

Also, this lab will definitely be submitted as a Jupyter Notebook.

**Comment by jmorrise** [comment]
Got it, I won't make large changes to the math then. 

@shanemcq I'll plan on it being a notebook lab. Note that if Facial Recognition _and_ Fourier 1&2 are notebooks, SVD doesn't necessarily need to be one (it could be, but that gives the students 4 notebook labs in a row).

**Comment by shanemcq18** [comment]
I think having several notebooks in a row is a good idea. The repetition will help them to get used to the concept of doing a lab as a presentation. But you're right, SVD is a little border line...

**Comment by jmorrise** [comment]
Also SVD does have code that ought to go through a test driver (the compact SVD that the students write themselves definitely should). That would be easier if it weren't a notebook.

**Comment by tannert** [comment]
If we're going to introduce PCA, I think we should refer to the eigenfaces instead as principal components and explain some more of the intuition behind PCA.  My reasoning is that PCA is used in many different fields (it crops up in remote sensing all the time), and students who understand what it is on a _qualitative_ level, independent of its applications to eigenfaces, will be able to recognize it and use it better when they see it in later work.  Also, the whole project makes more sense to me when I think of U_s as a matrix of principle components.

**Comment by tylerjarvis** [comment]
Once again, the most important thing to get across about PCA is that it is just another name for SVD.

I have not seen the current version of the lab, but it sounds like it needs some editing to 
1. clarify that while SVD is what we mathematicians call it, some people in other fields call it PCA
2. explain correctly what the SVD is telling us in this setting, including the "principle components"
3. Give better intuition about eigenfaces etc.

**Comment by tylerjarvis** [comment]
Note that Jessica is right.  Least squares is not why we are using SVD in this problem.  SVD is about identifying the most important directions (principle components), and then Schmidt-Eckart-Mirky-Young says that dropping out the less-important components will give you the best low-rank approximation.  The low rank approx is cheaper to use, compute etc, so the problem becomes tractable, whereas without SVD and low =-rank approximation, it is completely uncomputable--just way too big.

**Comment by shanemcq18** [comment]
See [the Wikipedia article](https://en.wikipedia.org/wiki/Principal_component_analysis#Singular_value_decomposition) on PCA for an explanation of why PCA = SVD.
