### ISSUE TITLE
Web Scraping [Fall 2016]

### ISSUE THREAD

**Issue by cnrrobertson** [Foundations-of-Applied-Mathematics/Lab-Development#1305]
Outline of changes for WebScraping 1:
- [x] Problem 3:
    - [x] Change location to after 'tag properties' section
    - [x] Incorporate that section into the problem
    - [x] Change wording of question to better match problem 4
- [x] Eliminate problem 4 part 2. It is basically a repeat of part 1
- [x] Fill out objective statement
- [x] Remove instances of the second person
- [x] Proofread lab to align better with Lab Standards
- [x] Provide better explanations for viewing prettified form of html code
- [x] Change wording of questions to explain how code will be submitted?
- [x] Update solutions file
- [x] Create spec file

**Comment by sgiddens** [comment]
Outline of changes for WebScraping 1:
[ ] Problem 3:
    [ ] Change location to after 'tag properties' section
    [ ] Incorporate that section into the problem
    [ ] Change wording of question to better match problem 4
[ ] Eliminate problem 4 part 2. It is basically a repeat of part 1
[ ] Fill out objective statement

**Comment by shanemcq18** [comment]
@tkchris93 is there anything else you want to do on these before we put them up?

**Comment by sgiddens** [comment]
Outline of changes for web scraping 2:

- [ ] Create solutions file
    - [ ] Problem 1
    - [ ] Problem 2
    - [ ] Problem 3
    - [ ] Problem 4
    - [ ] Problem 5
    - [ ] Problem 6
- [ ] Problem 1
    - [ ] Change to say save the page source from the link?
    - [ ] Clarify that it wants a numpy array
- [ ] Problem 2
- [ ] Problem 3
    - [ ] Have problem say to make the list and graph it
- [ ] Problem 4
- [ ] Problem 5
    - [ ] Change to 'Use selenium to return a list'
    - [ ] Add information before this problem on downloading selenium, geckodriver,
and updating everything (move this here from first paragraph
- [ ] Problem 6
    - [ ] Add information and code box for way to bypass problem when website doesn't 
load properly
- [ ] Fix typos
- [ ] Create spec file
