### ISSUE TITLE
1-D Optimization [Fall 2016]

### ISSUE THREAD

**Issue by mikeproudfoot** [Foundations-of-Applied-Mathematics/Lab-Development#1306]
- [x] Introduction to 1-D Optimization
- [x] 1-D Search
- [x] Bisection
- [x] Golden Ratio
- [x] Recap of Newton’s Method
- [x] Secant Method
- [x] Backtracking and Wolfe conditions (this is sort of necessitates a discussion of n-D optimization)
  - [x] Intro to Wolfe conditions
  - [x] Backtracking to Armijo conditions

**Comment by shanemcq18** [comment]
Notes from the meeting on Oct 6:
- The lab objective should contain basic motivation and outline. Right now it's kind of purposeless. Maybe move some of the stuff from the Line Search subheading?
- Open-ended questions are hard to deal with in problem statements. How could we modify Problem 2 so it isn't quite so open-ended?
- Consider finding a function with a painful derivative, but which we can use the Golden or Bisection methods to minimize.
- Eliminate the huge function declaration in Problem 3-5 (describe the function, then include the function declaration in the spec file).
- Can we find a function with an easy first derivative and a hard second derivative for the Secant method?
- Put hints on their own line, surrounded by parentheses, without italics.
- Gradient operators shouldn't be used if we're only doing 1-d optimization.
- Probably do both Armijo and Wolfe conditions.
- Consider timing `scipy.optimize.line_search()` against the previous methods.
- A good application to use `scipy.optimize.line_search()`?
- Might consider looking into `auto_grad` (for automatic differentiation).
- Email Michael about illustrations?

**Comment by shanemcq18** [comment]
See #1347 for suggestions for future improvement.
