### ISSUE TITLE
Web Tech [Fall 2016]

### ISSUE THREAD

**Issue by cnrrobertson** [Foundations-of-Applied-Mathematics/Lab-Development#1311]
The Web Technologies labs for Volume 3B are at the moment barren. They need to be filled with more information, reorganized, and problems that illustrate their usefulness need to be created. The list of adjustments is as follows:

WebTech1:
- [x] Switch location with WebTech2
- [x] Rewrite lab objective
- [x] Rewrite introduction to reflect importance
- [x] Add more description for JSON, XML, DOM, and Element Tree Sections
- [x] Switch order of XML and JSON and explain advantages?
- [x] Add reference to previous lab for instruction on "datetime" object in Problem 1
- [x] Redo Element Tree example in iPython with output displayed and clean comments
- [x] Add description and problem with Pickle to Additional Material
- [x] Create solutions file
- [x] Create spec file
- [ ] Pull html from online source with "requests" from previous lab, make it XML using xml library, put into ElementTree, and creating Python objects to do computations with

WebTech2:
- [x] Switch location with WebTech1
- [x] Rewrite objective
- [x] Rewrite introduction and protocol layer description stressing application
- [x] Rewrite TCP Server example in iPython to show output
- [x] Add problem to find information in pulled data using "requests" library
- [x] Add problem using HTTP server and TCP server/client to create chat between students
- [x] Create solutions file
- [x] Create spec file

**Comment by shanemcq18** [comment]
You might want to coordinate with @tkchris93 about how much you talk about the `datetime` object, since that might be discussed in the time series lab that he just drafted (Pandas 4).
