### ISSUE TITLE
Unit Testing [Fall 2016]

### ISSUE THREAD

**Issue by mmorrise** [Foundations-of-Applied-Mathematics/Lab-Development#1337]
- [x] Change the lab objective to reflect that unit testing is not just for software developers but is an effective way for students to test the code in their other labs: 

> "Convey the importance of unit testing in code, especially in the corporate world. Unit testing in python is easy, valuable, and powerful. Help students understand how they can use unit testing to become a more effect and productive programmer".

Change the introduction to unit testing:
- [x] Explain what testing is, and stress that it is not something only that only serious software engineers should do, but that they can use it in their labs and projects
- [x] Define unit testing
- [x] Remove the software engineering example (or replace it with a more understandable)

Make the following changes to the section on pytest:
- [x] Make the explanation of what and assert is part of the text rather than a note
- [x] Make a note explaining that "test" must be in the name of both the file and the method
- [x] Make a separate section on coverage, and give a definition of coverage before it is used in example code
- [x] Change the coverage example to the output of the empty solutions files
- [x] Change the Fibonacci method to be a method which returns the smallest prime factor of a number
- Include a diagram which demonstrates coverage of the new method mentioned above
- [x] Explain the motivation for fixtures before they are introduced
- [x] Remove the problem which asks the student to test the linked list class

Make the following changes to the section on Test Driven Design:
- [x] Expand the explanation of this section and mention more of the motivations for TDD
- [x] Change the last problem to be a program which plays the card game Set
    - [x] Write one problem where they write the unit tests for Set
    - [x]  Write a second problem where they write code to match their unit tests

- [x] Add a section on pdb - the python debugger

- [x] Write an answer key for both the solutions file and test_solutions file

**Comment by shanemcq18** [comment]
@mmorrise We probably need a section about using the debugger in python. It's called pdb (for Python debugger); see [the documentation here](https://docs.python.org/2/library/pdb.html). This might be something that we have a problem on, or just mention in passing, or that gets thrown into Additional Material, but it needs to be there somewhere.

**Comment by shanemcq18** [comment]
Closing this for now, but @mmorrise I want you to send the illustrator an idea for the figure to explain coverage sometime soon.
